[Desktop Entry]
Encoding=UTF-8
UntranslatedGenericName=Photivo Export
Name=Photivo Export
Name[ca]=Photivo Export
Name[ca@valencia]=Photivo Export
Name[cs]=Photivo Export
Name[da]=Photivo Export
Name[de]=Photivo Export
Name[el]=Photivo Export
Name[es]=Photivo Export
Name[et]=Photivo Export
Name[fi]=Photivo Export
Name[fr]=Photivo Export
Name[ga]=Photivo Export
Name[gl]=Photivo Export
Name[hu]=Photivo Export
Name[ia]=KXMLSaluteMundo
Name[is]=KXMLHallóHeimur
Name[it]=Photivo Export
Name[kk]=Photivo Export
Name[ko]=Photivo Export
Name[lt]=Photivo Export
Name[mr]=KXMLहेल्लोवर्ल्ड
Name[nb]=KXML Hallo_verden
Name[nl]=KXML-HelloWorld
Name[pl]=Photivo Export
Name[pt]=Photivo Export
Name[pt_BR]=Olá mundo KXML
Name[ro]=Photivo Export
Name[ru]=Photivo Export
Name[sk]=Photivo Export
Name[sl]=Photivo Export
Name[sr]=КДЕ‑ИксМЛ-здраво-свете
Name[sr@ijekavian]=КДЕ‑ИксМЛ-здраво-свете
Name[sr@ijekavianlatin]=KDE-XML-zdravo-svete
Name[sr@latin]=KDE-XML-zdravo-svete
Name[sv]=KXML Hello World
Name[tr]=Photivo Export
Name[uk]=Photivo Export
Name[x-test]=xxPhotivo Exportxx
Name[zh_CN]=Photivo Export
Name[zh_TW]=Photivo Export
Comment=A tool for exporting to Photivo
Comment[ca]=Una demostració de l'eina kipi que utilitza la tecnologia XML-GUI del KDE
Comment[ca@valencia]=Una demostració de l'eina kipi que utilitza la tecnologia XML-GUI del KDE
Comment[cs]=Ukázkový nástroj kipi využívající technologii KDE XML-GUI
Comment[da]=Et demo KIPI-værktøj der bruger KDE XML-GUI-teknologi
Comment[de]=Demo eines KIPI-Moduls. das die KDE-Technologie XML-GUI verwendet
Comment[el]=Ένα εργαλείο επίδειξης kipi με χρήση τεχνολογίας KDE XML-GUI
Comment[es]=Una herramienta kipi de demostración que usa la tecnología XML-GUI de KDE
Comment[et]=KIPI demotööriist, mis kasutab KDE XML-GUI tehnoloogiat
Comment[fi]=KDE:n XML-GUI-teknologiaa käyttävä KIPI-työkaludemo
Comment[fr]=Un outil KIPI de démonstration utilisante la technologie d'interface dgraphique XML de KDE
Comment[gl]=Unha ferramenta de demostración de kipi que emprega a tecnoloxía XML-GUI de KDE
Comment[hu]=Egy KDE XML-GUI technológiát használó demó kipi eszköz
Comment[ia]=Un instrumento de demonstration de kipi que usa technologia KDE XML-GUI
Comment[is]=Prófunar-kipi-verkfæri sem notar KDE XML-GUI tæknina
Comment[it]=Un'estensione dimostrativa di KIPI che usa la tecnologia XML-GUI di KDE
Comment[kk]=KDE XML-GUI технологиясын қолданатың демо kipi құралы
Comment[ko]=KDE XML-GUI를 사용하는 KIPI 도구 데모
Comment[lt]=Kipi demo įrankis naudojantis KDE XML-GUI technologiją
Comment[mr]=केडीई XML-GUI तंत्रज्ञान वापरणारे एक डेमो किपि साधन
Comment[nb]=Et kipi demo-verktøy som bruker KDEs XML-GUI-teknologi
Comment[nl]=Een demo kipi-hulpmiddel die KDE XML-GUI technologie gebruikt
Comment[pl]=Demonstracyjne narzędzie kipi używające technologi KDE XML-GUI
Comment[pt]=Uma ferramenta de demonstração do KIPI que usa a tecnologia XML-GUI do KDE
Comment[pt_BR]=Uma ferramenta do KIPI que usa a tecnologia KDE XML-GUI
Comment[ro]=Unealtă kipi demonstrativă folosind tehnologia KDE XML-GUI
Comment[ru]=Тестовый инструмент KIPI по использованию технологии XML-GUI KDE
Comment[sk]=Ukážkový kipi nástroj používajúci technológiu KDE XML-GUI
Comment[sl]=Predstavitveno orodje KIPI, ki uporablja tehnologijo KDE XML-GUI
Comment[sr]=Демонстрациона КИПИ алатка на технологији КДЕ‑овог ИксМЛ ГУИ‑ја
Comment[sr@ijekavian]=Демонстрациона КИПИ алатка на технологији КДЕ‑овог ИксМЛ ГУИ‑ја
Comment[sr@ijekavianlatin]=Demonstraciona KIPI alatka na tehnologiji KDE‑ovog XML GUI‑ja
Comment[sr@latin]=Demonstraciona KIPI alatka na tehnologiji KDE‑ovog XML GUI‑ja
Comment[sv]=Ett KIPI-verktyg för demonstration av KDE:s XML-GUI-teknologi
Comment[tr]=KDE XML-GUI teknolojisini kullanan bir demo kipi aracı
Comment[uk]=Тестовий інструмент KIPI щодо використання технології XML-GUI KDE
Comment[x-test]=xxA demo kipi tool using KDE XML-GUI technologyxx
Comment[zh_CN]=使用 KDE XML-GUI 技术的 kipi 演示程序
Comment[zh_TW]=示範用的 kipi 工具，使用 KDE XML-GUI 技術
ServiceTypes=KIPI/Plugin
Type=Service
#Icon=script-error
X-KDE-Library=kipiplugin_photivoexport
X-KIPI-ReqFeatures=
X-KIPI-PluginCategories=Image
X-KIPI-BinaryVersion=${KIPI_SO_VERSION}
author=Kevin Dalley, kevin at kelphead dot org
